### ISSUE TITLE
Conflicting bazel_version definitions

### ISSUE THREAD

**Issue by Dig-Doug** [protocolbuffers/upb#214]
`upb` and `rules_foreign_cc` both define `bazel_version` files and they conflict with each other.

https://github.com/bazelbuild/rules_foreign_cc/blob/a0dc109915cea85909bef586e2b2a9bbdc6c8ff5/workspace_definitions.bzl#L91

https://github.com/protocolbuffers/upb/blob/master/bazel/workspace_deps.bzl#L7

I'm guessing they should be prefixed with the library name, e.g. upb_bazel_version.

**Comment by haberman** [comment]
We should be able to remove the bazel_version check now, I think. The Bazel versions that were causing problems are now obsolete.

**Comment by matthewsot** [comment]
Thanks for opening this issue, it helped me pin down a build issue I've been having since upgrading to Bazel 1.1.0.

In case it's useful for anyone else, I've done a (probably naive) removal of references to the offending ``bazel_version`` in https://github.com/matthewsot/upb/commit/10a18cc12c2ebbcc0ed3aac1e61ae75d9bfc69d8 that worked for me (and can send a PR if desired).

**Comment by haberman** [comment]
All bazel_version checking is gone since https://github.com/protocolbuffers/upb/pull/258.
