### ISSUE TITLE
make testlua fails

### ISSUE THREAD

**Issue by bgmerrell** [protocolbuffers/upb#41]
Trying to run the lua bindings tests with Linux x86_64 (Ubuntu) and Lua 5.1, I get:

```
bgmerrell@oberon:~/code/upb$ make testlua USER_CPPFLAGS=`pkg-config lua5.1 --cflags`
CC -fPIC upb/pb/compile_decoder.c
CC -fPIC upb/pb/decoder.c
CC -fPIC upb/pb/encoder.c
CC -fPIC upb/pb/glue.c
CC -fPIC upb/pb/textprinter.c
CC -fPIC upb/pb/varint.c
AR lib/libupb.pb_pic.a
CC -fPIC upb/descriptor/descriptor.upb.c
CC -fPIC upb/descriptor/reader.c
AR lib/libupb.descriptor_pic.a
CC -fPIC upb/def.c
CC -fPIC upb/env.c
CC -fPIC upb/handlers.c
CC -fPIC upb/refcounted.c
CC -fPIC upb/shim/shim.c
CC -fPIC upb/symtab.c
CC -fPIC upb/table.c
CC -fPIC upb/upb.c
AR lib/libupb_pic.a
CC upb/bindings/lua/upb.c
CC upb/bindings/lua/upb/pb.c
LUA tests/bindings/lua/test_upb.lua
    ...............

406 Assertions checked.

Testsuite finished (15 passed, 0 failed, 0 errors).
LUA tests/bindings/lua/test_upb.pb.lua
lua: error loading module 'upb.pb_c' from file 'upb/bindings/lua/upb/pb_c.so':
        upb/bindings/lua/upb/pb_c.so: undefined symbol: lupb_openlib
stack traceback:
        [C]: ?
        [C]: in function 'require'
        upb/bindings/lua/upb/pb.lua:3: in main chunk
        [C]: in function 'require'
        tests/bindings/lua/test_upb.pb.lua:4: in main chunk
        [C]: ?
Makefile:444: recipe for target 'testlua' failed
make: *** [testlua] Error 1
```

I see the lupb_openlib symbol in the upb/bindings/lua/upb_c.so and upb/bindings/lua/upb/pb_c.so shared objects.

**Comment by haberman** [comment]
Is there a specific reason you are using Lua 5.1? This is known not to work with Lua 5.1 (though it does work with LuaJIT), because it depends on a feature that was only added in Lua 5.2 and LuaJIT. Specifically, `package.loadlib(so, "*")` as a way of loading with `RTLD_GLOBAL`.

I would ideally like to work with Lua 5.1 also, but this is unfortunately a somewhat complicated issue. The short version is: if you express these dependencies between C modules at the OS level, you have to worry about also setting `LD_LIBRARY_PATH`  and `DYLD_LIBRARY_PATH`, and the build system becomes more platform-dependent.

I changed this earlier this year to *not* use OS-level library dependencies (see: https://github.com/google/upb/commit/51cf616dab63ba65c30cc58f0e5a61724aa4f731). I was hoping that by resolving these dependencies at the Lua layer, it would be less platform-specific. But unfortunately my solution doesn't work with Lua 5.1.

I'm open to potentially changing this to a more OS-integrated approach, particularly if Lua 5.1 compatibility is really required. But I'd want to be sure that the solution works on OS X (which has quite a different OS-level dynamic linker). I'd also want the upbc wrapper script to set `LD_LIBRARY_PATH` and `DYLD_LIBRARY_PATH` so it can be run from any directory. I think it would also be required to make `luaopen_upb_pb_c()` call `luaopen_upb_c()`, so that if a user said `require("upb.pb")` without requiring "upb" first, the library would still work.

**Comment by bgmerrell** [comment]
Thanks for the response @haberman.

We are using 5.1 for a couple of reasons.  1) the distros we are able to use only have dev packages for 5.1 and 2) our Go bindings don't yet support LuaJIT, which we would like to move toward.

In fact, we aren't yet using upb either; we require the ability to serialize protobufs in Lua and as far as I can tell that isn't implemented yet.

I wasn't aware this was such a complicated issue, so I am OK with this not going in.  Maybe we'll be on LuaJIT by the time we are ready to be using upb.

**Comment by haberman** [comment]
Things have changed a lot since we had this exchange. The core upb library has changed a lot and the Lua bindings are currently experimental. I'm going to close this for now -- hopefully the Lua bindings will be fully supported someday and could be useful to you then.
